---
title: "Number of Seeds"
author: "Shusei Eshima"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{GenSimDataLDA}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r warning=FALSE, message=FALSE, echo = FALSE}
# package_folder <- "/Users/Shusei/Dropbox/Study/Project/ImaiText/topicdict"
# setwd(package_folder)
# devtools::document() ; devtools::install() ; library(topicdict)
library(knitr)
knitr::opts_chunk$set(comment = "")
```


```{r, warning=FALSE, message=FALSE}
library(topicdict)
library(quanteda)
library(tibble)
library(ggplot2)
library(dplyr)
library(topicmodels)
iter_num <- 250
extra_k <- 2
```

# Fit Seeded LDA
We'll use the Bara data, and seeds extracted from the dictionary.  
These are all in package `extdata`:
```{r, warning=FALSE, message=FALSE, fig.width=7, fig.height=5}
doc_folder <- system.file(file.path("extdata", "bara_paras"), package = "topicdict")
seed_file <- system.file(file.path("extdata", "bara_seeds.txt"), package = "topicdict")

## turn this flat file of seeds into a (quanteda dictionary) list as it would be used
seed_list <- Map(function(x){ unlist(strsplit(x, " ")) }, 
                 Filter(function(x){ !grepl(x, pattern = "#") }, # remove comments
                        readLines(seed_file)))

# Original topic names from Bara dictionary
names(seed_list) <- c("advocacy", "legal", "medical", "moral", "procedural", "social")
dict <- dictionary(seed_list)
dict

stops <- setdiff(c(stopwords("english"), letters), 
                  c("he", "his", "him", "himself", "she", "hers", "her", "herself"))

# Changing the number of seeds for each topic
seed_list[[1]] <- seed_list[[1]][1:7]
seed_list[[2]] <- seed_list[[2]][1:3]
seed_list[[3]] <- seed_list[[3]][1:8]
seed_list[[5]] <- seed_list[[5]][1:5]

explore_ <- explore(list.files(doc_folder, pattern="txt", full.names=T),
             remove_numbers = FALSE, # For simulation, make it false
             remove_punct = TRUE,
             remove_symbols = TRUE,
             remove_separators = TRUE,
						 stopwords=stops)
explore_$visualize_dict_prop(seed_list)
```

```{r, warning=FALSE, message=FALSE}
set.seed(225)


model <- topicdict_model(list.files(doc_folder, pattern="txt", full.names=T), extra_k=extra_k,
                         dict, stopwords = stops)
res <- topicdict_train(model, iter = 300)
original_vocabulary <- model$vocab
```

```{r, warning=FALSE, message=FALSE}
post <- topicdict::posterior(res)
top_terms(post, n = 25, show_seed = T)
```

