---
title: "Rice 0.2% Rule"
author: "Shusei Eshima"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{GenSimDataLDA}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r warning=FALSE, message=FALSE, echo = FALSE}
# package_folder <- "/Users/Shusei/Dropbox/Study/Project/ImaiText/topicdict"
# setwd(package_folder)
# devtools::document() ; devtools::install() ; library(topicdict)
library(knitr)
knitr::opts_chunk$set(comment = "")
```


```{r, warning=FALSE, message=FALSE}
library(topicdict)
library(quanteda)
library(tibble)
library(ggplot2)
library(dplyr)
library(topicmodels)
iter_num <- 500
extra_k <- 2
```

```{r, warning=FALSE, message=FALSE}
create_model <- function(folder, extra_k, 
                                     seed_file_name="", seed_list = NULL,
                                     cull_seed=NULL){

  # cull_seed: Which row (=topic) and column (=number of seed) to use

  set.seed(225)

  docs <- list.files(folder, pattern = "*.txt", full.names = TRUE)

  if(seed_file_name != ""){
    seed_file <- paste0(data_folder, data_folder_name, "/", seed_file_name)
    seeddata <- invisible(readr::read_csv(seed_file))
  }

  if(!is.null(cull_seed)){
    seeddata <- seeddata[1:cull_seed[1], 1:cull_seed[2]]
  }

  if(is.null(seed_list)){
    seed_list <- as.list( apply(seeddata, 1, function(x){return(paste0(x, collapse=" "))}) )
  }
  names(seed_list) <- 1:length(seed_list)
  dict <- quanteda::dictionary(seed_list)

  stops <- c(stopwords("english"), letters)
  model <- topicdict_model(docs,
               dict = dict, extra_k = extra_k,
               remove_numbers = FALSE, # For simulation, make it false
               remove_punct = TRUE,
               remove_symbols = TRUE,
               remove_separators = TRUE,
               stopwords=stops)

  return(model)
}
```

```{r, warning=FALSE, message=FALSE}
library(topicmodels)
library(tidytext)
library(tm)
get_lda_result <- function(data_folder, iter_num, k){

	corpus <- Corpus(DirSource(data_folder))
	dtm <- DocumentTermMatrix(corpus, control = list(stopwords = T, tolower = T, 
														 stemming = F, wordLengths = c(1, Inf)))

	rowTotals <- apply(dtm , 1, sum) #Find the sum of words in each Document
	empty <- rownames(dtm[rowTotals == 0, ])  
	if(length(empty)!=0){
		print(empty)
		stop("Texts are empty")
	}

	lda <- LDA(dtm, k = k, method="Gibbs", control = list(seed = 225, iter=iter_num))
	topics <- tidy(lda, matrix = "beta")

	top_terms <- topics %>%
		group_by(topic) %>%
		top_n(10, beta) %>%
		ungroup() %>%
		arrange(topic, -beta)

	assign <- augment(lda, dtm)
	assign %>% 
				mutate(Word=term) %>%
				group_by(.topic, Word) %>%
				summarise(counts = sum(count)) %>%
				ungroup() %>%
				group_by(.topic) %>% 
				top_n(10, counts) %>%
				mutate(topicsum = sum(counts)) %>%
				arrange(.topic, desc(counts) ) %>%
				ungroup() %>%
				mutate(Proportion = counts / topicsum * 100,
							 Estimated = paste0("Est", .topic)) -> res

	unique_topic <- unique(res$.topic)[order(unique(res$.topic))]
	words <- c()
	for(topic in unique_topic){
		w <- res %>% filter(.topic==get('topic')) %>% select(Word)
		words <- c(words, paste(w$Word, collapse=" "))
	}
	topwords_table <- tibble(Topic=unique_topic, Words=words) %>% knitr::kable()
	print(topwords_table)
}
```


# Use Rice Data
```{r, warning=FALSE, message=FALSE}
data_folder <- "/Users/Shusei/Desktop/temp/Data/Rice500"
```

# Explore the data
```{r, warning=FALSE, message=FALSE, fig.width=6, fig.height=4}
# Explore
docs <- list.files(data_folder, pattern = "*.txt", full.names = TRUE)
explore_ <- explore(docs,
             remove_numbers = TRUE, # For simulation, make it false
             remove_punct = TRUE,
             remove_symbols = TRUE,
             remove_separators = TRUE)
explore_$top_words()
```

# High Proportion 
Original paper tries k=25 and k=100
```{r, warning=FALSE, message=FALSE, fig.width=7, fig.height=5}
# Select seed based on tf-idf
seed_list <- list(c("court case law judgment"), # high law
             c("debt company property tax"), # high financial
             c("officer congress state government")) # high state 
explore_$visualize_dict_prop(seed_list)

model <- create_model(data_folder, seed_list=seed_list, extra_k=22)
res <- topicdict_train(model, iter = iter_num)
post <- topicdict::posterior(res)
top_terms(post, n = 25, show_seed = T)
```

## Analysis
### Modelfit
```{r, warning=FALSE, message=FALSE, fig.width=6, fig.height=4}
diagnosis_model_fit(post, start=2)
```

```{r, warning=FALSE, message=FALSE, fig.width=10, fig.height=6.5}
get_lda_result(data_folder, iter=iter_num, k=25)
```


# Proportion around 0.2
Original paper tries k=25 and k=100
```{r, warning=FALSE, message=FALSE, fig.width=7, fig.height=5}
# Select seed based on tf-idf
seed_list <- list(c("constitution order rule opinion"), 
             c("interest payment tax bank"), 
             c("jurisdiction congress government officer"))  
explore_$visualize_dict_prop(seed_list)

model <- create_model(data_folder, seed_list=seed_list, extra_k=22)
res <- topicdict_train(model, iter = iter_num)
post <- topicdict::posterior(res)
top_terms(post, n = 25, show_seed = T)
```

## Analysis
### Modelfit
```{r, warning=FALSE, message=FALSE, fig.width=6, fig.height=4}
diagnosis_model_fit(post, start=2)
```

# Proportion smaller than 0.2
Original paper tries k=25 and k=100
```{r, warning=FALSE, message=FALSE, fig.width=7, fig.height=5}
# Select seed based on tf-idf
seed_list <- list(c("justice supreme judge legal"), 
             c("creditor stock equity business"), 
             c("election citizen town commissioner"))  
explore_$visualize_dict_prop(seed_list)

model <- create_model(data_folder, seed_list=seed_list, extra_k=22)
res <- topicdict_train(model, iter = iter_num)
post <- topicdict::posterior(res)
top_terms(post, n = 25, show_seed = T)
```

## Analysis
### Modelfit
```{r, warning=FALSE, message=FALSE, fig.width=6, fig.height=4}
diagnosis_model_fit(post, start=2)
```

