---
title: "Vignette Title"
author: "Vignette Author"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
library(dplyr)
library(lubridate)
library(quanteda)
library(lme4)
library(topicdict)
```

```{r}
dd <- read.csv("ttrule/speaker_meeting_unique.csv", 
               stringsAsFactors = FALSE, sep = ";", row.names = 1)
# extract some meeting dates
dd$date <- ymd(gsub("[a-zA-Z.]", "", dd$file_id))
dd$text <- dd$Speech
dd$Speech <- NULL
spkrs <- strsplit(gsub("[.]", "", dd$Speaker), " ")
dd$name <- unlist(lapply(spkrs, function(x) x[length(x)])) # last element
corp <- corpus(dd, docid_field = "file_id", text_field = "text") 
```

## Next up

For different numbers of topic, run LDA and sLDA and measure 
stability of ranking / overlap.

```{r}
library(topicmodels)

dtm <- dfm(corp, remove_numbers = TRUE, 
           remove_punct = TRUE, 
           remove_separators = TRUE,
           remove_symbols = TRUE,
           remove = stopwords(),
           stem = TRUE)

set.seed(12345)
dtm <- as.DocumentTermMatrix(dtm)

lda_mod5 <- LDA(dtm, k = 5, method = "gibbs", 
                control = list(seed = 12345, verbose = TRUE))
lda_mod5_terms <- terms(lda_mod5, 50)
lda_mod10 <- LDA(dtm, k = 10, method = "gibbs", 
                 control = list(seed = 12345, verbose = TRUE)) 
lda_mod10_terms <- terms(lda_mod10, 50)

lda_mod15 <- LDA(dtm, k = 15, method = "gibbs", 
                 control = list(seed = 12345, verbose = TRUE)) 
lda_mod15_terms <- terms(lda_mod15, 50)

lda_mod20 <- LDA(dtm, k = 20, method = "gibbs", 
                 control = list(seed = 12345, verbose = TRUE)) 
lda_mod20_terms <- terms(lda_mod20, 50)

lda_mod25 <- LDA(dtm, k = 25, method = "gibbs", 
                 control = list(seed = 12345, verbose = TRUE)) 
lda_mod25_terms <- terms(lda_mod25, 50)

lda_mod30 <- LDA(dtm, k = 30, method = "gibbs", 
                 control = list(seed = 12345, verbose = TRUE)) 
lda_mod30_terms <- terms(lda_mod30, 50)
```

Now for the topicdict versions

```{r}
infl <- unlist(strsplit("inflation inflationary core basis expectations ",
                        "funds price point prices pressures", " "))
out <- unlist(strsplit(c("market wal company business trucking trucks companies",
                       "sales shipping construction wage staff medical layoff",
                       "residential nonfarm productivity compensation",
                       "slack", "unemployment", "employment", "labor"), " "))
dict <- dictionary(list(inflation = infl, output = out))
```

```{r}
mod5 <- topicdict_model(corp, dict = dict, 
                        extra_k = 3, 
                        remove_numbers = TRUE, 
                        remove_punct = TRUE, 
                        remove_separators = TRUE,
                        remove_symbols = TRUE,
                        stem_language = "english",
                        stopwords = stopwords())
mod <- topicdict_train(mod5, iter = 300)
post <- posterior(mod5)
td_mod5_terms <- top_terms(post, 50)

mod10 <- topicdict_model(corp, dict = dict, 
                        extra_k = 8, 
                        remove_numbers = TRUE, 
                        remove_punct = TRUE, 
                        remove_separators = TRUE,
                        remove_symbols = TRUE,
                        stem_language = "english",
                        stopwords = stopwords())
mod <- topicdict_train(mod10, iter = 300)
post <- posterior(mod10)
td_mod10_terms <- top_terms(post, 50)

mod15 <- topicdict_model(corp, dict = dict, 
                        extra_k = 13, 
                        remove_numbers = TRUE, 
                        remove_punct = TRUE, 
                        remove_separators = TRUE,
                        remove_symbols = TRUE,
                        stem_language = "english",
                        stopwords = stopwords())
mod <- topicdict_train(mod15, iter = 300)
post <- posterior(mod15)
td_mod15_terms <- top_terms(post, 50)

mod20 <- topicdict_model(corp, dict = dict, 
                        extra_k = 18, 
                        remove_numbers = TRUE, 
                        remove_punct = TRUE, 
                        remove_separators = TRUE,
                        remove_symbols = TRUE,
                        stem_language = "english",
                        stopwords = stopwords())
mod <- topicdict_train(mod20, iter = 300)
post <- posterior(mod20)
td_mod20_terms <- top_terms(post, 50)

mod25 <- topicdict_model(corp, dict = dict, 
                        extra_k = 23, 
                        remove_numbers = TRUE, 
                        remove_punct = TRUE, 
                        remove_separators = TRUE,
                        remove_symbols = TRUE,
                        stem_language = "english",
                        stopwords = stopwords())
mod <- topicdict_train(mod25, iter = 300)
post <- posterior(mod25)
td_mod25_terms <- top_terms(post, 50)

mod30 <- topicdict_model(corp, dict = dict, 
                        extra_k = 28, 
                        remove_numbers = TRUE, 
                        remove_punct = TRUE, 
                        remove_separators = TRUE,
                        remove_symbols = TRUE,
                        stem_language = "english",
                        stopwords = stopwords())
mod <- topicdict_train(mod30, iter = 300)
post <- posterior(mod30)
td_mod30_terms <- top_terms(post, 50)
```

```{r}
delabel_terms <- function(x){
  x <- data.frame(x, stringsAsFactors = FALSE)
  for (i in 1:ncol(x)){
    x[[i]] <- unlist(lapply(strsplit(x[[i]], " "), function(v){ v[1] }))
  }
  x
}

compare_top_terms <- function(x, y){
  d <- ncol(x) # y is same
  m <- matrix(0, nrow = d, ncol = d)
  for (xi in 1:d)
    for (yi in 1:d)
      m[xi,yi] <- m[yi,xi] <- length(intersect(x[,xi], y[,yi]))
  m
}
```

Comparisons (what is the overlap in top terms at each topic number?

```{r}
print(5)
compare_top_terms(delabel_terms(td_mod5_terms), lda_mod5_terms)
print(10)
compare_top_terms(delabel_terms(td_mod10_terms), lda_mod10_terms)
print(15)
compare_top_terms(delabel_terms(td_mod15_terms), lda_mod15_terms)
print(20)
compare_top_terms(delabel_terms(td_mod20_terms), lda_mod20_terms)
print(25)
compare_top_terms(delabel_terms(td_mod25_terms), lda_mod25_terms)
print(30)
compare_top_terms(delabel_terms(td_mod30_terms), lda_mod30_terms)
```

```{r}
print("5-10")
comp5_10 <- compare_top_terms(delabel_terms(td_mod5_terms)[,1:2],
                  delabel_terms(td_mod10_terms)[,1:2])
print("10-15")
comp10_15 <- compare_top_terms(delabel_terms(td_mod10_terms)[,1:2],
                  delabel_terms(td_mod15_terms)[,1:2])
print("15-20")
comp15_20 <- compare_top_terms(delabel_terms(td_mod15_terms)[,1:2],
                  delabel_terms(td_mod20_terms)[,1:2])
print("20-25")
comp20_25 <- compare_top_terms(delabel_terms(td_mod20_terms)[,1:2], 
                  delabel_terms(td_mod25_terms)[,1:2])
print("25-30")
comp25_30 <- compare_top_terms(delabel_terms(td_mod25_terms)[,1:2], 
                  delabel_terms(td_mod30_terms)[,1:2])
print("5-15")
comp5_15 <- compare_top_terms(delabel_terms(td_mod5_terms)[,1:2],
                  delabel_terms(td_mod15_terms)[,1:2])
print("5-20")
comp5_20 <- compare_top_terms(delabel_terms(td_mod5_terms)[,1:2],
                  delabel_terms(td_mod20_terms)[,1:2])
print("5-25")
comp5_25 <- compare_top_terms(delabel_terms(td_mod5_terms)[,1:2],
                  delabel_terms(td_mod25_terms)[,1:2])
print("5-30")
comp5_30 <- compare_top_terms(delabel_terms(td_mod5_terms)[,1:2],
                  delabel_terms(td_mod30_terms)[,1:2])
print("10-20")
comp10_20 <- compare_top_terms(delabel_terms(td_mod10_terms)[,1:2],
                  delabel_terms(td_mod20_terms)[,1:2])
print("10-25")
comp10_25 <- compare_top_terms(delabel_terms(td_mod10_terms)[,1:2],
                  delabel_terms(td_mod25_terms)[,1:2])
print("10-30")
comp10_30 <- compare_top_terms(delabel_terms(td_mod10_terms)[,1:2],
                  delabel_terms(td_mod30_terms)[,1:2])
print("15-25")
comp15_25 <- compare_top_terms(delabel_terms(td_mod15_terms)[,1:2],
                  delabel_terms(td_mod25_terms)[,1:2])
print("15-30")
comp15_30 <- compare_top_terms(delabel_terms(td_mod15_terms)[,1:2],
                  delabel_terms(td_mod30_terms)[,1:2])
print("20-30")
comp20_30 <- compare_top_terms(delabel_terms(td_mod20_terms)[,1:2],
                  delabel_terms(td_mod30_terms)[,1:2])

overlap <- diag(6)
overlap[1,2] <- sum(diag(comp5_10)) / sum(comp5_10)
overlap[1,3] <- sum(diag(comp5_15))/ sum(comp5_15)
overlap[1,4] <- sum(diag(comp5_20))/ sum(comp5_20)
overlap[1,5] <- sum(diag(comp5_25))/ sum(comp5_25)
overlap[1,5] <- sum(diag(comp5_30))/ sum(comp5_30)
overlap[2,3] <- sum(diag(comp10_15))/ sum(comp10_15)
overlap[2,4] <- sum(diag(comp10_20))/ sum(comp10_20)
overlap[2,5] <- sum(diag(comp10_25))/ sum(comp10_25)
overlap[2,6] <- sum(diag(comp10_30))/ sum(comp10_30)
overlap[3,4] <- sum(diag(comp15_20))/ sum(comp15_20)
overlap[3,5] <- sum(diag(comp15_25))/ sum(comp15_25)
overlap[3,6] <- sum(diag(comp15_30))/ sum(comp15_30)
overlap[4,5] <- sum(diag(comp20_25))/ sum(comp20_25)
overlap[4,6] <- sum(diag(comp20_30))/ sum(comp20_30)
overlap[5,6] <- sum(diag(comp25_30))/ sum(comp25_30)

print(Matrix(overlap, sparse = TRUE)*100, digits = 1)
```


