---
title: "Estimate the effect of document topic proportions on covariates"
output: 
  html_document:
    toc: true
---

```{r setup II, include=FALSE, eval=TRUE}
knitr::opts_chunk$set(eval = T, echo = TRUE)
```

```{r, warning=FALSE, message=FALSE, fig.align='center', include = FALSE}
library(keyATM)
data(keyATM_data_bills)
bills_cov <- keyATM_data_bills$cov
dim(bills_cov)  # We have 140 documents and a single covariate

bills_time_index <- keyATM_data_bills$time_index
bills_time_index <- as.integer(bills_time_index - 100)

library(quanteda)
bills_dfm <- keyATM_data_bills$doc_dfm  # quanteda object
keyATM_docs <- keyATM_read(bills_dfm)

bills_keywords <- list(
                       Education = c("education", "child", "student"),
                       Law       = c("court", "law", "attorney"),
                       Health    = c("public", "health", "program"),
                       Drug      = c("drug", "treatment")
                      )
```

## Fitting the model
You can fit any of the three **keyATM** models. To get credible intervals, make sure to use `store_theta` option.

```{r, warning=FALSE, message=FALSE, fig.align='center'}
out1 <- keyATM(docs              = keyATM_docs,    # text input
               no_keyword_topics = 3,              # number of topics without keywords
               keywords          = bills_keywords, # keywords
               model             = "base",         # select the model
               options           = list(seed = 100, store_theta = TRUE)
              )

out2 <- keyATM(    
               docs              = keyATM_docs,    # text input
               no_keyword_topics = 3,              # number of topics without keywords
               keywords          = bills_keywords, # keywords
               model             = "covariates",   # select the model
               model_settings    = list(covariates_data = bills_cov),
               options           = list(seed = 100, store_theta = TRUE)
              )

out3 <- keyATM(    
               docs              = keyATM_docs,    # text input
               no_keyword_topics = 3,              # number of topics without keywords
               keywords          = bills_keywords, # keywords
               model             = "dynamic",          # select the model
               model_settings    = list(time_index = bills_time_index,
                                        num_states = 5),
               options           = list(seed = 100, store_theta = TRUE)
              )
```

## Regressing document topic proportion on covariates
```{r, warning=FALSE, message=FALSE, fig.align='center'}
coef <- estimate_coefficients(out1, covariates_data = bills_cov)
plot(coef, topics = 1:3, variables = c("RepParty"))
```


```{r, warning=FALSE, message=FALSE, fig.align='center'}
coef <- estimate_coefficients(out2, covariates_data = bills_cov)
plot(coef, topics = 1:3, variables = c("RepParty"))
```


```{r, warning=FALSE, message=FALSE, fig.align='center'}
coef <- estimate_coefficients(out3, covariates_data = bills_cov)
plot(coef, topics = 1:3, variables = c("RepParty"))
```


