---
title: "Customizing Plots"
output: 
  html_document:
    toc: true
---


```{r, include=FALSE, warning=FALSE, message=FALSE, fig.align='center'}
library(keyATM)
library(quanteda)
library(magrittr)
library(dplyr)
library(tibble)
data(data_corpus_inaugural, package = "quanteda")
data_corpus_inaugural <- head(data_corpus_inaugural, n = 58)
data_tokens <- tokens(data_corpus_inaugural,
                      remove_numbers = TRUE, 
                      remove_punct = TRUE, 
                      remove_symbols = TRUE,
                      remove_separators = TRUE,
                      remove_url = TRUE) %>%
                 tokens_tolower() %>%
                 tokens_remove(c(stopwords("english"), 
                               "may", "shall", "can",
                               "must", "upon", "with", "without")) %>%
                 tokens_select(min_nchar = 3)
                
data_dfm <- dfm(data_tokens) %>%
               dfm_trim(min_termfreq = 5, min_docfreq = 2)
keywords <- list(Government     = c("laws", "law", "executive"),
                 Congress       = c("congress", "party"),
                 Peace          = c("peace", "world", "freedom"),
                 Constitution   = c("constitution", "rights"),
                 ForeignAffairs  = c("foreign", "war"))
keyATM_docs <- keyATM_read(data_dfm)

# Get meta information (time stamp)
vars <- docvars(data_corpus_inaugural)
head(vars)
# Divide by a decade
# Timestamp should start with 1 (the variable "Period")
vars %>%
  as_tibble() %>%
  mutate(Period = (vars$Year - 1780) %/% 10 + 1) -> vars_period

```

You can extract values used in a plot with the `values_fig()` function.
Here we have a time trend plot from [keyATM Dynamic](keyATM_dynamic.html).
```{r, warning=FALSE, message=FALSE, fig.align='center'}
out <- keyATM(docs              = keyATM_docs,                         
              no_keyword_topics = 3,                                   
              keywords          = keywords,                      
              model             = "dynamic",                           
              model_settings    = list(time_index = vars_period$Period,
                                       num_states = 5),                
              options           = list(seed = 250, store_theta = TRUE, thinning = 5))
fig_timetrend <- plot_timetrend(out, time_index_label = vars$Year, xlab = "Year", width = 5)
fig_timetrend
```

The `values_fig()` function returns a tibble used to create the plot.
```{r, warning=FALSE, message=FALSE, fig.align='center'}
values_fig(fig_timetrend)
```

We can use it to customize the figure.
```{r, warning=FALSE, message=FALSE, fig.align='center', fig.height = 4, fig.width = 6.5}
library(ggplot2)
values <- values_fig(fig_timetrend)

values %>%
  filter(Topic %in% c("1_Government", "3_Peace")) %>%  # extract two topics
  filter(time_index >= 1900) %>%  # from 1900
ggplot(., aes(x = time_index, y = Point, group = Topic)) +
  geom_ribbon(aes(ymin = Lower, ymax = Upper), fill = "gray75") +
  geom_line(size = 0.8, aes(colour = Topic)) +
  geom_point(shape = 5, size = 0.9) +
  xlab("Year") + ylab(expression(paste("Mean of ", theta))) +
  annotate("text", x = 2005, y = 0.12, label = "Government", colour = "#F8766D") +
  annotate("text", x = 2005, y = 0.28, label = "Peace", colour = "#00BFC4") +
  ggthemes::theme_economist_white(gray_bg = FALSE) +
  theme(legend.position = "none")
```

The `values_fig()` function works with other **keyATM** plot functions. Check the reference for details.


