---
title: "Semi-automated Dictionary"
author: "Shusei Eshima"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{GenSimDataLDA}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r warning=FALSE, message=FALSE, echo = FALSE}
# package_folder <- "/Users/Shusei/Dropbox/Study/Project/ImaiText/topicdict"
# setwd(package_folder)
# devtools::document() ; devtools::install() ; library(topicdict)
library(knitr)
knitr::opts_chunk$set(comment = "")
```


```{r, warning=FALSE, message=FALSE}
library(topicdict)
library(quanteda)
library(tibble)
library(ggplot2)
library(dplyr)
library(topicmodels)
iter_num <- 250
extra_k <- 2
```

We'll use the Bara data, and seeds extracted from the dictionary.  
These are all in package `extdata`:
```{r, warning=FALSE, message=FALSE, fig.width=7, fig.height=5}
doc_folder <- system.file(file.path("extdata", "bara_paras"), package = "topicdict")

# Original topic names from Bara dictionary
stops <- setdiff(c(stopwords("english"), letters), 
                  c("he", "his", "him", "himself", "she", "hers", "her", "herself"))

explore_ <- explore(list.files(doc_folder, pattern="txt", full.names=T),
             remove_numbers = FALSE, # For simulation, make it false
             remove_punct = TRUE,
             remove_symbols = TRUE,
             remove_separators = TRUE,
             stopwords=stops)
```

```
# semiauto_dictionary(explore_class_obj, num_seeds, prop_center, window)
# num_seed should be a vector
# c(1,2,3): Number of seed is 1, 2, and 3 (three seeded topics)
# proortion center and window: the range to randomly select seeds 

#                                       center=0.2
# window=0.05|       |-----------------------|----------------|
#       words| word1  word2  word3  word4  word5  word6  word7  word8  
#  proportion|  0.12   0.15   0.17   0.18   0.20   0.22   0.25   0.30
#  
#  randomly pick from word2 to word7
```

```{r, warning=FALSE, message=FALSE}
semiauto_dictionary <- function(eobj, num_seeds, 
                            prop_center=rep(0.3, length(num_seeds)),
                            window = rep(0.05, length(num_seeds))){

  if(length(num_seeds) != length(prop_center) | length(num_seeds) != length(window) ){
    stop("Length of prop_center and num_seeds should be equal to the number of seeded topics.")
  }

  seed_list <- list()
  for(i in 1:length(num_seeds)){
    num <- num_seeds[[i]]
    min <- prop_center[i] - window[i]
    max <- prop_center[i] + window[i]
    eobj$data %>%
      filter(`Proportion(%)` > get("min") & `Proportion(%)` < get("max")) -> temp

    if(nrow(temp) == 0){
      stop(paste0("There is no word that meets the specified condition. Recheck topic "), i, ".")
    } else if(nrow(temp) < num){
      warning(paste0("The number of words that match the condition is fewer than the number you specidied. Recheck topic "), i, ".")
      seed_list <- c(seed_list, list(paste(temp$Word, collapse=" ")))
    }else{
      select <- sample(1:nrow(temp), num)
      seed_list <- c(seed_list, list(paste(temp$Word[select], collapse=" ")))
    }
  }

  return(seed_list)
}
```

```{r, warning=FALSE, message=FALSE, fig.width=6.5, fig.height=4.5}
seed_list <- semiauto_dictionary(explore_,
                                 num_seeds = c(2,2,3,4),
                                 prop_center = c(0.9, 0.5, 0.3, 0.2))
explore_$visualize_dict_prop(seed_list)
```



