---
title: "Progress Report"
author: "Shusei Eshima"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{GenSimDataLDA}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r warning=FALSE, message=FALSE, echo = FALSE}
# package_folder <- "/Users/Shusei/Dropbox/Study/Project/ImaiText/topicdict"
# setwd(package_folder)
# devtools::document() ; devtools::install() ; library(topicdict)
savepath <- "/Users/Shusei/Dropbox/Study/Project/ImaiText/topicdict/vignettes/"
iter_num <- 800
library(knitr)
knitr::opts_chunk$set(comment = "")
```


```{r, warning=FALSE, message=FALSE}
library(topicdict)
library(purrr)
library(quanteda)
library(tibble)
library(ggplot2)
library(dplyr)
library(topicmodels)
```

# Prepare Functions
```{r warning=FALSE, message=FALSE, include=FALSE}
source("create_simulation_data.R")
source("create_heatmap_functions.R")

# Use a part of seed words
use_part_of_seed <- function(x, use=1:5){
  res <- x[use] # use part of seed
  return(res)
}
```

Create model function:
```{r, warning=FALSE, message=FALSE}
create_model <- function(docs, seed_list, extra_k){
  set.seed(225)
  names(seed_list) <- 1:length(seed_list)
  dict <- quanteda::dictionary(seed_list)
  model <- topicdict_model(docs,
               dict = dict, extra_k = extra_k,
               remove_numbers = FALSE, 
               remove_punct = TRUE,
               remove_symbols = TRUE,
               remove_separators = TRUE)

  return(model)
}
```

```{r, warning=FALSE, message=FALSE}
# Check dispersion
tidy_seededlda_out <- function(model, res, n=15, show=F){
  # Create a nested data frame which contains W and Z
  post <- topicdict::posterior(res)
  topwords <- top_terms(post, n=n)
  topwords <- data.frame(topwords)
  colnames(topwords) <- paste0("EstTopic", 1:ncol(topwords))
  topwords %>%
    tidyr::gather(., key=EstTopic, value=Word) %>%
    mutate(Word = gsub("\\s.*$", "", Word)) -> otidy

  if(show){
    num_seededtopic <- length(model$seeds)
    print(top_terms(post, n))
  }

  return(otidy)
}


list_to_tibble <- function(lobj){
  # Flatten list and get a tibble
  obj_len <- lobj %>% map(length) %>% flatten_int()
  element <- lobj %>% flatten_chr()

  tibble(SeedTopic = rep(paste0("EstTopic", 1:length(obj_len)), obj_len),
         Word=element
         ) -> res
  return(res)
}

count_appearence_list <- function(otidy, lobj){
  all_words <- lobj %>% flatten_chr()
  SeedTopicName <- paste0("EstTopic", 1:length(lobj))

  otidy %>% 
    right_join(., list_to_tibble(get("lobj")), by="Word") %>%
    mutate(count = ifelse(is.na(EstTopic), 0, 1)) %>%
    group_by(Word, SeedTopic) %>%
    summarize(count = sum(count)) -> organized


  organized %>%
    ggplot(., aes(x=factor(count))) +
    geom_histogram(stat="count") +
    xlab("Number of Topics") + ylab("Count") + ggtitle("Words Split across Topics") +
    theme_bw(base_size=15) +
    theme(plot.title = element_text(hjust = 0.5)) -> g1

  organized %>%
    ggplot(., aes(x=factor(count))) +
    geom_histogram(stat="count") +
    facet_wrap(~ SeedTopic, ncol=3) +
    xlab("Number of Topics") + ylab("Count") + ggtitle("Words Split across Topics") +
    theme_bw(base_size=15) +
    theme(plot.title = element_text(hjust = 0.5)) -> g2

  # Only check topics with seed
  otidy %>% 
    filter(EstTopic %in% get("SeedTopicName")) %>%
    right_join(., list_to_tibble(get("lobj")), by="Word") %>%
    mutate(count = ifelse(is.na(EstTopic), 0, 1)) %>%
    group_by(Word, SeedTopic) %>%
    summarize(count = sum(count)) -> organized_

  organized_ %>%
    ggplot(., aes(x=factor(count))) +
    geom_histogram(stat="count") +
    facet_wrap(~ SeedTopic, ncol=3) +
    xlab("Number of Topics") + ylab("Count") + ggtitle("Words Split across Topics\n(Only topics with keywords)") +
    theme_bw(base_size=15) +
    theme(plot.title = element_text(hjust = 0.5)) -> g3

  return(list(g1, g2, g3))
}
```

```{r, warning=FALSE, message=FALSE}
library(tm)

get_lda_result <- function(doc_folder, seed_list, iter_num, k, topicvec=1:k, show_n=15, showtop=F){

  # Prepare Data
  corpus <- Corpus(DirSource(doc_folder))
  strsplit_space_tokenizer <- function(x)
      unlist(strsplit(as.character(x), "[[:space:]]+"))

  dtm <- DocumentTermMatrix(corpus,
                           control = list(tokenize=strsplit_space_tokenizer, 
                           stopwords = F, tolower = T, 
                           stemming = F, wordLengths = c(1, Inf)))

  lda <- LDA(dtm, k = k, control = list(seed = 225, iter=iter_num), method="Gibbs")


  all_words <- seed_list %>% flatten_chr()

  tidytext::tidy(lda) %>%
    group_by(topic) %>%
    top_n(show_n, beta) -> topwords_
	topwords_ %>%
    rename(topics = topic, Word = term) %>%
    select(-beta) %>%
    right_join(., list_to_tibble(get("seed_list")), by="Word") %>%
    mutate(count = ifelse(is.na(topics), 0, 1)) %>%
    group_by(Word, SeedTopic) %>%
    summarize(count = sum(count)) -> organized


  organized %>%
    ggplot(., aes(x=factor(count))) +
    geom_histogram(stat="count") +
    xlab("Number of Topics") + ylab("Count") + ggtitle("Words Split across Topics") +
    theme_bw(base_size=15) +
    theme(plot.title = element_text(hjust = 0.5)) -> g1

  organized %>%
    ggplot(., aes(x=factor(count))) +
    geom_histogram(stat="count") +
    facet_wrap(~ SeedTopic, ncol=3) +
    xlab("Number of Topics") + ylab("Count") + ggtitle("Words Split across Topics") +
    theme_bw(base_size=15) +
    theme(plot.title = element_text(hjust = 0.5)) -> g2

	if(showtop){
		topwords_ %>%
			ungroup() %>%
			arrange(topic, desc(beta)) %>%
			select(-beta) -> temp
		twdf <- temp %>% filter(topic==1) %>% select(term) %>% as.matrix() %>% data.frame()
		for(k in 2:length(unique(temp$topic))){
			temp %>% filter(topic==k) %>% select(term) %>% as.matrix() %>% data.frame() -> add
			twdf <- cbind(twdf,
										add[1:15,])
		}
		colnames(twdf) <- 1:length(unique(temp$topic))
		print(twdf)
	}

  return(list(g1, g2))
}
```


# Amy's Data Look in Detail
## Read Data
```{r, warning=FALSE, message=FALSE}
doc_folder <- paste0("/Users/Shusei/Dropbox/Study/My_Research/TreeStructuredTopicModel/Papers/replication/Catalinac/data/docs") # Data from original data Document-Term Matrix
docs <- list.files(doc_folder, pattern = "*.txt", full.names = TRUE)
```

## Self-Selected Keywords
```{r, warning=FALSE, message=FALSE}
# Remove overlapping words for better comparison
seed_list <- list(c("農業 整備 漁業 開発 水産"), # agriculture, fishing industry
                  c("税 消費 暮らし 景気 税金"), # tax
                  c("介護 高齢 保険 長寿 健康"), # aging society
                  c("軍事 戦争 軍 自衛隊 平和"))
seed_list <- lapply(seed_list, function(x){strsplit(x, " ")[[1]]})
```

## K = 80
```{r, warning=FALSE, message=FALSE, fig.width=8.5, fig.height=6.5}
# SeededLDA eight keywords
model <- create_model(docs, seed_list, extra_k=76)
res <- topicdict_train(model, iter = iter_num)
count_appearence_list(tidy_seededlda_out(model, res, show=T), seed_list)
```

### Standard LDA
```{r, warning=FALSE, message=FALSE, fig.width=8.5, fig.height=6.5}
get_lda_result(doc_folder, seed_list, iter_num, k=80, showtop=T)
```


## K = 100
```{r, warning=FALSE, message=FALSE, fig.width=8.5, fig.height=6.5}
# SeededLDA eight keywords
model <- create_model(docs, seed_list, extra_k=96)
res <- topicdict_train(model, iter = iter_num)
count_appearence_list(tidy_seededlda_out(model, res, show=T), seed_list)
```

### Standard LDA
```{r, warning=FALSE, message=FALSE, fig.width=8.5, fig.height=6.5}
get_lda_result(doc_folder, seed_list, iter_num, k=100, showtop=T)
```


## Original Keywords
```{r, warning=FALSE, message=FALSE}
# Remove overlapping words for better comparison
topic52 <- c("農業 産業 整備 漁業 開発")
topic62 <- c("復興 連立 被災 災害 ひと")
topic63 <- c("政治 主義 自由 社会 民主")
topic20 <- c("税 消費 廃止 国民 日本")
topic58 <- c("企業 教育 中小 充実 図る")

seed_list <- list(topic52, topic62, topic63, topic20, topic58)
seed_list <- lapply(seed_list, function(x){strsplit(x, " ")[[1]]})
```


## K = 80
```{r, warning=FALSE, message=FALSE, fig.width=8.5, fig.height=6.5}
# SeededLDA eight keywords
model <- create_model(docs, seed_list, extra_k=76)
res <- topicdict_train(model, iter = iter_num)
count_appearence_list(tidy_seededlda_out(model, res, show=T), seed_list)
```

### Standard LDA
```{r, warning=FALSE, message=FALSE, fig.width=8.5, fig.height=6.5}
get_lda_result(doc_folder, seed_list, iter_num, k=80, showtop=T)
```

## K = 100
```{r, warning=FALSE, message=FALSE, fig.width=8.5, fig.height=6.5}
# SeededLDA eight keywords
model <- create_model(docs, seed_list, extra_k=96)
res <- topicdict_train(model, iter = iter_num)
count_appearence_list(tidy_seededlda_out(model, res, show=T), seed_list)
```

### Standard LDA
```{r, warning=FALSE, message=FALSE, fig.width=8.5, fig.height=6.5}
get_lda_result(doc_folder, seed_list, iter_num, k=100, showtop=T)
```


# New Visualization

## Middle
```{r, warning=FALSE, message=FALSE, fig.width=8.5, fig.height=6.5}
# How many "true" topic can keywords collect?
multiple_simulations(trueK=c(5,15,25,35), estimatedK=c(5,15,25,35))
```

```{r, warning=FALSE, message=FALSE, fig.width=8.5, fig.height=6.5}
# How many "true" topic can keywords collect?
multiple_simulations(trueK=c(5,15,25,35), estimatedK=c(5,15,25,35),
                     seed_contamination=2)
```

## Low
```{r, warning=FALSE, message=FALSE, fig.width=8.5, fig.height=6.5}
# How many "true" topic can keywords collect?
multiple_simulations(trueK=c(5,15,25,35), estimatedK=c(5,15,25,35), seed_p_base=0.25)
```

```{r, warning=FALSE, message=FALSE, fig.width=8.5, fig.height=6.5}
# How many "true" topic can keywords collect?
multiple_simulations(trueK=c(5,15,25,35), estimatedK=c(5,15,25,35), seed_p_base=0.25,
                     seed_contamination=2)
```

## High
```{r, warning=FALSE, message=FALSE, fig.width=8.5, fig.height=6.5}
# How many "true" topic can keywords collect?
multiple_simulations(trueK=c(5,15,25,35), estimatedK=c(5,15,25,35), seed_p_base=0.1)
```

```{r, warning=FALSE, message=FALSE, fig.width=8.5, fig.height=6.5}
# How many "true" topic can keywords collect?
multiple_simulations(trueK=c(5,15,25,35), estimatedK=c(5,15,25,35), seed_p_base=0.1,
                     seed_contamination=2)
```
