# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Read files from the quanteda dfm (this is the same as dgCMatrix) 
#'
#' @param dfm a dfm input (sparse Matrix)
#' @param W_raw an object to return
#' @param vocab a vector of vocabulary
#'
#' @keywords internal
read_dfm_cpp <- function(dfm, W_raw, vocab) {
    .Call(`_keyATM_read_dfm_cpp`, dfm, W_raw, vocab)
}

#' Run the Collapsed Gibbs sampler for the keyATM Base
#'
#' @param model A initialized model
#' @param iter Required number of iterations
#'
#' @keywords internal
keyATM_fit_base <- function(model, iter = 0L) {
    .Call(`_keyATM_keyATM_fit_base`, model, iter)
}

#' Run the Collapsed Gibbs sampler for the keyATM covariates
#'
#' @param model A initialized model
#' @param iter Required number of iterations
#'
#' @keywords internal
keyATM_fit_cov <- function(model, iter = 0L) {
    .Call(`_keyATM_keyATM_fit_cov`, model, iter)
}

#' Run the Collapsed Gibbs sampler for the keyATM Dynamic
#'
#' @param model A initialized model
#' @param iter Required number of iterations
#'
#' @keywords internal
keyATM_fit_HMM <- function(model, iter = 0L) {
    .Call(`_keyATM_keyATM_fit_HMM`, model, iter)
}

#' Run the Collapsed Gibbs sampler for the keyATM label
#'
#' @param model A initialized model
#' @param iter Required number of iterations
#'
#' @keywords internal
keyATM_fit_label <- function(model, iter = 0L) {
    .Call(`_keyATM_keyATM_fit_label`, model, iter)
}

#' Run the Collapsed Gibbs sampler for weighted LDA
#'
#' @param model A initialized model
#' @param iter Required number of iterations
#'
#' @keywords internal
keyATM_fit_LDA <- function(model, iter = 0L) {
    .Call(`_keyATM_keyATM_fit_LDA`, model, iter)
}

#' Run the Collapsed Gibbs sampler for weighted LDA with covariates
#'
#' @param model A initialized model
#' @param iter Required number of iterations
#'
#' @keywords internal
keyATM_fit_LDAcov <- function(model, iter = 0L) {
    .Call(`_keyATM_keyATM_fit_LDAcov`, model, iter)
}

#' Run the Collapsed Gibbs sampler for the weighted LDA with HMM model
#'
#' @param model A initialized model
#' @param iter Required number of iterations
#'
#' @keywords internal
keyATM_fit_LDAHMM <- function(model, iter = 0L) {
    .Call(`_keyATM_keyATM_fit_LDAHMM`, model, iter)
}

