# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Run the Gibbs sampler
#'
#' @param model A model, from \code{init} or a previous invocation of \code{train}
#' @param iter Required number of iterations
#' @param output_per Show log-likelihood and perplexity per this number during the iteration
#'
#' @export
topicdict_train <- function(model, iter = 0L, output_per = 10L) {
    .Call('_topicdict_topicdict_train', PACKAGE = 'topicdict', model, iter, output_per)
}

